services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ABCD1234
      POSTGRES_DB: quizzlyDB
    depends_on:
      - db
      - chromadb
    networks:
      - quizly-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - quizly-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ABCD1234
      POSTGRES_DB: quizzlyDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quizly-network

  chromadb:
    build:
      context: ./chromadb
    ports:
      - "8001:8001"
    networks:
      - quizly-network

volumes:
  postgres_data:

networks:
  quizly-network:
    driver: bridge